//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public int ID { get; set; }
        public string BloodName { get; set; }
        public int ID_Hospital { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
