//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Enrollment
    {
        public int Id { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        [StringLength(50, ErrorMessage = "Grade cannot be longer than 50 characters")]
        public string Grade { get; set; }
        public Nullable<int> ID_MedicalExaminations { get; set; }
    
        public virtual MedicalExaminations MedicalExaminations { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
