//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Enrollment = new HashSet<Enrollment>();
            this.MedicalExaminations = new HashSet<MedicalExaminations>();
        }
        
        public int ID { get; set; }
        [StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters")]
        public string PatientName { get; set; }
        [StringLength(50, ErrorMessage = "Surname cannot be longer than 50 characters")]
        public string PatientSurname { get; set; }
        [StringLength(11, ErrorMessage = "Personal number must be 11 characters")]
        [MinLength(11, ErrorMessage = "Personal number must be 11 characters")]
        public string SSN { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        public Nullable<int> ID_Doctor { get; set; }
        public Nullable<int> ID_Blood { get; set; }
        public Nullable<int> ID_Hospital { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual Hospital Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalExaminations> MedicalExaminations { get; set; }
    }
}
